version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: django-bootstrap4
    versions:
    - 2.3.1
  - dependency-name: django-cors-headers
    versions:
    - 3.6.0
  - dependency-name: whitenoise
    versions:
    - 5.1.0
  rebase-strategy: disabled
