language: python
dist: xenial
python:
- '3.6'
- '3.7'
- '3.8'
env:
  global:
  - DOCKER_USERNAME='ocstravisci'
  - secure: mXSj8NvShTODQ7dLru7xymaZ03Ve5NFxOMaC6C2c2TX7Bv8AnrH1PJatD+GmHGaCHcKtxzReKwtw5NXLoeKH0XeWxvxbYTWGoaUsocn62AEhBk4EqUGM1Ns5MyQFSCqgFrO7eLtWiSTQybdUZZz75hMeIWPRnPv5owKtghvCPfCgfCsuhSsIlhhmzHJQZxc2kZFx661HBi9j4m0vTub/p67mzHI/3nm/Xye9g1aOFg1WQeu29Kbm0ufr5diuxE8ahMI8wDwjQG6Zs5FBUTxrciwOZou8b+DAq5y39wZ35+3xW+F0QbrkdJ2b//1btQBQCEddvSaIbVuFx5hZTqVMJy8tce8cWFfPT8oTPi6t5b48/f6LiQCs9Zx3bRcSOlkaY5hVXNMTmdo4DtrYfPAf5FJlOLgDqxW8OINRHOTWCN83DtTQ+VbbvTp/ZYijY+EqEVc8/dDRBzThtJdCFbdH1GQ2T0CBT9G8IY82aKfQwubNcBGk7Xa/RP5LiPCyp5PNbcQuGJVzkhRn/o2SUtdS8RUA61bLILjnq+wN0PmqnbAnZZXDJrjs+pIVOmcbou9d9Xyh+cZj8sOHm7L7mWtFwpQGgYf1alssDdf5yKPkPqTbsRMQC2qG48NW/zfxY70JXdToL4cFQc9f7qUXKt48O0Q/WPUOVCz234ARAoHI670=
services:
- docker
install:
- pip install -U coverage coveralls
- pip install -r requirements.txt
script: coverage run manage.py test
after_success: coveralls
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- export IMAGE=observatorycontrolsystem/downtime:${TRAVIS_TAG}
- docker build -t $IMAGE .
deploy:
- provider: script
  script: docker push $IMAGE
  skip_cleanup: true
  on:
    tags: true
