language: python
dist: xenial
python:
- '3.6'
- '3.7'
- '3.8'
env:
  global:
  - DOCKER_USERNAME='ocstravisci'
  - secure: SJpy9X59TdQCOz3C3rUb8n0Yi3gI4PobZLWn5GW+2HLOaMNHj4klpV11tPdCg5AxfgQ5zS9NpwB8rqUzD9BpYlhwBBVSwRNtgItAgrA6+R1+bRaOXNCJSkfYcTPKNbQo13HQ4l1OJh/tVF9D26FCxNtwVHXWsN4P5uvciqLDUBFQ84YtLor9yLWCq7hJIYKLkj+AJG5wQjm2nqBPJmtRaoRpoFCcGrHRFuVmCBPL8PaBRxNr4Ff+tmrAvPW9ASt7l9L64qpYk5fEK5LzQc+RFg9w+AmAKO2YSSqDYlv+5soA0znxrPCdJeZo9YY38l0vZULrmi0iqb6yLg3vn6UdPIWOAaC1CjDSpgP9bYp8+8MpgXwbZBfJYoX2yiLAgbNwfTAV7GwgVjRZYUxPvHSDXVdSzVVtjoO138yAJ+V7sdvK2oRj7rERqWV2UhnjgRIqaMFvxKY9o7GxK0CpirYIT0R80OfsJbE2owYdBuzJZsvEFXUOTGh0xLReWq5SGT7IB6XhCZT0A/L45RooD2M2Km4+kNVUur37taNq/HkBUbIVJClHgxfgYlBqHx3kL59oFmF1BICKW3HnoQXaiOAx/Q6czwe60kjY/4b3cnQ2mntIYEdqO1L+kgMOatoDtx/Y0MHD9DllgXVB9shihuV4qOeQR7K1Ep+CUp7CY6QE3yg=
services:
- docker
install:
- pip install -U coverage coveralls
- pip install -r requirements.txt
script: coverage run manage.py test
after_success: coveralls
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- export IMAGE=observatorycontrolsystem/downtime:${TRAVIS_TAG}
- docker build -t $IMAGE .
deploy:
- provider: script
  script: docker push $IMAGE
  skip_cleanup: true
  on:
    tags: true
