language: python
dist: xenial
python:
- '3.6'
- '3.7'
- '3.8'
env:
  global:
  - DOCKER_USERNAME='ocstravisci'
  - secure: G7hWi4s6QYrhJYs0EyaeCzayrKcxAXVTJXWbBkPGgK6n8fQG2HL2NqLcX8sd7Tg73XhjsoYC5+iXb71MGh15yLDotTWfTdJ6zIWwOf5LGae6WphS1ZiAlgjAkqegvQNCvjRTrXJFSInLDkRUBhMTvHrVEk802p2Oqk1vuWedh5ubj4Rt71RMsLwR21uhI95Ra3JDIQIpL784lQAt8T5SrIXIsqaSwJ7Qf4oBRgHAgKgJw0CiuhN7Lc5POZ7Sh/8bK5IAQ+RstZ0aUvh8u3DbyVkiRjPmdb46w26M4SWyZyyYKHbRXDvu5niDVbfT08eBwIxTFkhQ4FFpyBphggrtgYPoUakw09inBc5EriIRpsZE26g8YjMx5CiTAonnKQRG97Uks/7jPIWg33NdQLESaljBDRZB1+AAeV87l3VCXXuEgXuehDcVbhWnXn+6ymLYG5shnZk+lCLPHe3nTFfx0ngMYLIShzcblM/s1rTtdWloFbytZLZZ8yMKOM347Ex9SmPLIsWZnFKiL/EdMNjcUotqiFGVxD3cchMr9QokNMRGJY/YM2bSdsKnXe/4Y1NDtKs++97LDR4JaGLG1B5WkAvwLGAC7oQ+6uqn6OpJk8tn6tB5breXWuYxDYs3xkh/T4gH7xFyTYV71OxRCVaeK2j74CYy1FqN5buR4auk9XU=
services:
- docker
install:
- pip install -U coverage coveralls
- pip install -r requirements.txt
script: coverage run manage.py test
after_success: coveralls
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- export IMAGE=observatorycontrolsystem/downtime:${TRAVIS_TAG}
- docker build -t $IMAGE .
deploy:
- provider: script
  script: docker push $IMAGE
  skip_cleanup: true
  on:
    tags: true
