language: python
dist: xenial
python:
- '3.6'
- '3.7'
- '3.8'
env:
  global:
  - DOCKER_USERNAME='ocstravisci'
  - secure: grFd5pFQLhPmSIv1Jv/UY4jJ+BwSD2MDS7n1G1Cp3nkPY/ZsI8q4/7UvVEZDw5hYjum1AwhWi5DPiEsAWbM5gyoR7ndjhU4FqRCRT/KfXmUshNoX6jO9qmy1KgOWJMyNnmJS2gaFRpo4s9+UWs14k4bLNXmsd/38JfYDYzNtSHzMwgGbInLclP7qHcmgplqAzh5AelzPgPRD9CM1mKXfGwfQDvlfjqYx96UqRAb+4f0ZKOq1VCDt4TIxT+2xYByhhEVFLwOo5PCKmyTf9bNEL6rjcaReL7nRcn1hQS0YYYKWEzyARS013J4yYoGwj9Uk3YCNQGtXHzEU9+QngZ8KEkPNGX91qT2eDVFvQSYhAoLYGDQq0hugorWIxeJAGPN5MXV7+r8H+w+4VFQatXAqKzj98qqlQzAkW0DBCFoMt8zUR7B7AG2oi0Mp/k7Uo9GDb+eoFe0K1EzS0QLKaDejOhSyOB3AkLVMNIsTvkHZPIWIXj8oLZqAEHG9R6gRnysHsafL9yA0E+vbjjdzpOQLEDZYu/AWz5iUfVx2GkxWr6+ldLoWtin3v3iiOuqh1FbdzEbjSlCaSk/99H+hvA6+Ifx4sNPJ0gIIMYtQwTEZt+k5KrcJNjzzjOeuQ2+9POngkEGiKKVDGIhEgwZWj/6y8RD6IapoUaz1X8O3xdZPfpw=
services:
- docker
install:
- pip install -U coverage coveralls
- pip install -r requirements.txt
script: coverage run manage.py test
after_success: coveralls
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- export IMAGE=observatorycontrolsystem/downtime:${TRAVIS_TAG}
- docker build -t $IMAGE .
deploy:
- provider: script
  script: docker push $IMAGE
  skip_cleanup: true
  on:
    tags: true
