[tool.poetry]
name = "downtime"
version = "2.6.0"
description = "Downtime API"
authors = ["OCS Authors"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12, <3.14"
django = "~6.0"
django-extensions = "^4.1"
django-filter = "^26"
django-bootstrap4 = "^26"
django-cors-headers = "^4.9"
djangorestframework = "^3.18"
ocs-authentication = "^0.2"
ocs-rise-set = "^0.6.6"
time-intervals = "^1"
requests = ">=2,<3"
whitenoise = "^6.12"
psycopg = {extras = ["c"], version = "^3.3.4"}
gunicorn = {version = "^26.0.0", extras = ["gevent"]}
pyyaml = ">=6.0"
uritemplate = "^4.2"
inflection = "^0.5.1"
setuptools-scm = "^10.3"
packaging = "^26.0"


[tool.poetry.group.dev.dependencies]
responses = ">=0.12,<1.0"
coverage = "^7.16"
coveralls = "^4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
