# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('site', models.CharField(max_length=3)),
                ('observatory', models.CharField(max_length=4)),
                ('telescope', models.CharField(max_length=4)),
                ('reason', models.CharField(blank=True, default='', max_length=3000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
