# Generated by Django 3.0.11 on 2021-01-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20170801_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downtime',
            old_name='observatory',
            new_name='enclosure',
        ),
        migrations.RenameField(
            model_name='downtime',
            old_name='updated',
            new_name='modified',
        ),
    ]
