# Generated by Django 3.0.11 on 2021-04-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210108_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='instrument_type',
            field=models.CharField(blank=True, default='', help_text='The instrument type in configuration db. If specified, downtime will only apply on this instrument type', max_length=255),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='enclosure',
            field=models.CharField(help_text='4 character enclosure code to apply downtime on, i.e. doma', max_length=4),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='reason',
            field=models.CharField(blank=True, default='', help_text='A descriptive reason for why this downtime exists', max_length=3000),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='site',
            field=models.CharField(help_text='3 character site code to apply downtime on', max_length=3),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='telescope',
            field=models.CharField(help_text='4 character telescope code to apply downtime on, i.e. 1m0a', max_length=4),
        ),
    ]
