# Extracted from https://github.com/jizt-it/jizt-api-spec/blob/main/.github/workflows/build-docs.yml
name: Build docs
on:
  push:
    branches:
      - feature/openapi-doc
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docs
      run: ./make-docs.sh
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3 # https://github.com/peaceiris/actions-gh-pages
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: mgdaily/mgdaily-test-github-pages.github.io
        publish_dir: /docs
        exclude_assets: '.github,openapi,.redocly.yaml,LICENSE,README.md,make.sh'