# Extracted from https://github.com/jizt-it/jizt-api-spec/blob/main/.github/workflows/build-docs.yml
name: Build docs
on:
  push:
    branches:
      - feature/openapi-doc
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONFIGDB_URL: http://configdb-dev
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build docs
      run: |
        python manage.py generateschema_mocked --file downtime.yaml
        npx redoc-cli bundle downtime.yaml
        mkdir docs; mv redoc-static.html docs/downtime.html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3 # https://github.com/peaceiris/actions-gh-pages
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: observatory-control-system/observatorycontrolsystem.github.io
        publish_dir: docs
        destination_dir: docs
        publish_branch: feature/openapi-doc
        keep_files: true
        exclude_assets: '.github,openapi,.redocly.yaml,LICENSE,README.md,make.sh'